baseURL = 'https://blog.wnwrght.co.uk/'
languageCode = 'en'
title = 'SW Blog'
theme = "archie"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
